framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
         # dsn: 'null://null' # désactive l'envoi de mail
        # envelope:
            # recipients: ['gadfellouiza@gmail.com'] # envoie tous les mails à cette adresse
