symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # durée de vie : 3600 
    # throttle_limit : 3600 
    # enable_garbage_collection : true