twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        contact_companyName: 'A.G Distribution'
        contact_address: '47 Rue jules Ferry'
        contact_zip: '91200'
        contact_city: 'Morsang sur Orge '
        contact_phone: '06 95 11 61 95 '
        contact_email: 'gadfel@icloud.com'

when@test:
    twig:
        strict_variables: true
